### PR TITLE
Correct a translation of Chinese Traditional

### PR DESCRIPTION
**Pull request by lest-day**

### CODE REVIEW

**Comment by rossjrw** [comment]
Thank you for the contribution @lest-day!

Here is a preview of what the source code of a notification delivered in Traditional Chinese would look like in a Wikidot PM. (I have also sent you a Wikidot message with this.) If you would like to make any amendments to it, please let me know.

<details><summary><b>Preview</b></summary>

```
Subject: [論壇提醒] 14 個新貼文
您好！這是您在 http://notifications.wikidot.com 訂閱的每小時提醒摘要，用於提醒您訂閱的討論區内發佈了新的討論貼文。

本服務正在追蹤：

* 0 個手動訂閱，可在[http://notifications.wikidot.com/redirect-to-your-config 您的個人設定]處設定。

* 自動訂閱討論區和讨论帖。[http://notifications.wikidot.com/faq#auto 了解自動訂閱內容的構成。]

本賬號（[[*user Notifier]]）是全自動運營的——任何對本私訊發送的回復都將會被忽略。如果您遇到了任何問題，請直接聯絡我（[[*user Croquembouche]]）。

-----

[[=]]
+ 📫️
[[/=]]

-----

++ My Wiki

+++ 其它

從 2 個討論區收到 14 條提醒

[[ul style="list-style-type: '📬️ '"]]
[[li]]
**討論區： [https://my-wiki.wikidot.com/forum/t-1 Post 1]**  -- [[date 10 format="%d %b %Y %H:%M:%S|agohover"]]
[[ul style="list-style-type: '📦️ '"]]
[[li]]
**回復： [https://my-wiki.wikidot.com/forum/t-1/#post-1 Post 1]** -- [[date 10 format="%d %b %Y %H:%M:%S|agohover"]]

[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-11 Post 11]** -- [[*user AnotherUser]] -- [[date 31 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-12 Post 12]** -- [[*user AnotherUser]] -- [[date 32 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[/ul]]
[[/li]]
[[li]]
**回復： [https://my-wiki.wikidot.com/forum/t-1/#post-2 Post 2]** -- [[date 20 format="%d %b %Y %H:%M:%S|agohover"]]

[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-21 Post 21]** -- [[*user AnotherUser]] -- [[date 51 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-22 Post 22]** -- [[*user AnotherUser]] -- [[date 52 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[/ul]]
[[/li]]
[[/ul]]
[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-1 Post 1]** -- [[*user AnotherUser]] -- [[date 11 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-2 Post 2]** -- [[*user AnotherUser]] -- [[date 12 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-1/#post-3 Post 3]** -- [[*user AnotherUser]] -- [[date 13 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[/ul]]
[[/li]]
[[li]]
**討論區： [https://my-wiki.wikidot.com/forum/t-2 Post 2]**  -- [[date 20 format="%d %b %Y %H:%M:%S|agohover"]]
[[ul style="list-style-type: '📦️ '"]]
[[li]]
**回復： [https://my-wiki.wikidot.com/forum/t-2/#post-1 Post 1]** -- [[date 10 format="%d %b %Y %H:%M:%S|agohover"]]

[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-11 Post 11]** -- [[*user AnotherUser]] -- [[date 41 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-12 Post 12]** -- [[*user AnotherUser]] -- [[date 42 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[/ul]]
[[/li]]
[[li]]
**回復： [https://my-wiki.wikidot.com/forum/t-2/#post-2 Post 2]** -- [[date 20 format="%d %b %Y %H:%M:%S|agohover"]]

[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-21 Post 21]** -- [[*user AnotherUser]] -- [[date 61 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-22 Post 22]** -- [[*user AnotherUser]] -- [[date 62 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Response...//##
[[/li]]
[[/ul]]
[[/li]]
[[/ul]]
[[ul style="list-style-type: '✉️ '"]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-1 Post 1]** -- [[*user AnotherUser]] -- [[date 21 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-2 Post 2]** -- [[*user AnotherUser]] -- [[date 22 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[li]]
**[https://my-wiki.wikidot.com/forum/t-2/#post-3 Post 3]** -- [[*user AnotherUser]] -- [[date 23 format="%d %b %Y %H:%M:%S|agohover"]]

**|** ##grey|//Contents...//##
[[/li]]
[[/ul]]
[[/li]]
[[/ul]]

-----

[[=]]
+ 📭️

-----

取消訂閱本提醒：http://notifications.wikidot.com/faq#stop
[[/=]]
```

</details>

**Comment by rossjrw** [comment]
Notifications can now be delivered in Traditional Chinese :) thank you!

**Comment by lest-day** [comment]
Hello, my account should be lestday233. lest-day is my stolen account.

**Comment by rossjrw** [comment]
Oops! Thanks for the correction, I did send that preview to the wrong account. I've now sent it to lestday233 and have updated the list of translation contributors accordingly.

**Comment by lest-day** [comment]
> Oops! Thanks for the correction, I did send that preview to the wrong account. I've now sent it to lestday233 and have updated the list of translation contributors accordingly.

Thank you.

**Pull request merged**
